-- Tests for PART VPD

EXEC APP_CTX_PKG.set_role('ROLE_ADMIN');
SELECT COUNT(*) FROM PART;

EXEC APP_CTX_PKG.set_role('ROLE_THUKHO');
SELECT COUNT(*) FROM PART;

EXEC APP_CTX_PKG.set_role('ROLE_KITHUATVIEN');
SELECT COUNT(*) FROM PART;

EXEC APP_CTX_PKG.set_role('ROLE_TIEPTAN');
SELECT COUNT(*) FROM PART; -- 0

EXEC APP_CTX_PKG.set_role('ROLE_KHACHHANG');
SELECT COUNT(*) FROM PART; -- 0


