-- Test scripts for VPD on STOCK tables
-- Run after creating context (SQL/VPD/init/02_app_context.sql), function (01_stock_vpd_function.sql), and policies (02_stock_vpd_add_policy.sql)

-- ADMIN xem full
EXEC APP_CTX_PKG.set_role('ROLE_ADMIN');
SELECT COUNT(*) AS CNT_ADMIN_IN        FROM STOCK_IN;
SELECT COUNT(*) AS CNT_ADMIN_IN_ITEM   FROM STOCK_IN_ITEM;
SELECT COUNT(*) AS CNT_ADMIN_OUT       FROM STOCK_OUT;
SELECT COUNT(*) AS CNT_ADMIN_OUT_ITEM  FROM STOCK_OUT_ITEM;

-- THUKHO xem full
EXEC APP_CTX_PKG.set_role('ROLE_THUKHO');
SELECT COUNT(*) AS CNT_THUKHO_IN        FROM STOCK_IN;
SELECT COUNT(*) AS CNT_THUKHO_IN_ITEM   FROM STOCK_IN_ITEM;
SELECT COUNT(*) AS CNT_THUKHO_OUT       FROM STOCK_OUT;
SELECT COUNT(*) AS CNT_THUKHO_OUT_ITEM  FROM STOCK_OUT_ITEM;

-- TIEPTAN không xem được
EXEC APP_CTX_PKG.set_role('ROLE_TIEPTAN');
SELECT COUNT(*) AS CNT_TIEPTAN_IN        FROM STOCK_IN;
SELECT COUNT(*) AS CNT_TIEPTAN_IN_ITEM   FROM STOCK_IN_ITEM;
SELECT COUNT(*) AS CNT_TIEPTAN_OUT       FROM STOCK_OUT;
SELECT COUNT(*) AS CNT_TIEPTAN_OUT_ITEM  FROM STOCK_OUT_ITEM;

-- KITHUATVIEN không xem được
EXEC APP_CTX_PKG.set_role('ROLE_KITHUATVIEN');
SELECT COUNT(*) AS CNT_KTV_IN        FROM STOCK_IN;
SELECT COUNT(*) AS CNT_KTV_IN_ITEM   FROM STOCK_IN_ITEM;
SELECT COUNT(*) AS CNT_KTV_OUT       FROM STOCK_OUT;
SELECT COUNT(*) AS CNT_KTV_OUT_ITEM  FROM STOCK_OUT_ITEM;

-- KHACHHANG không xem được
EXEC APP_CTX_PKG.set_role('ROLE_KHACHHANG');
SELECT COUNT(*) AS CNT_KH_IN        FROM STOCK_IN;
SELECT COUNT(*) AS CNT_KH_IN_ITEM   FROM STOCK_IN_ITEM;
SELECT COUNT(*) AS CNT_KH_OUT       FROM STOCK_OUT;
SELECT COUNT(*) AS CNT_KH_OUT_ITEM  FROM STOCK_OUT_ITEM;

-- Inspect policies
SELECT STOCK_VPD_PREDICATE(USER,'STOCK_IN') FROM dual;
SELECT object_owner, object_name, policy_name FROM user_policies WHERE object_name IN ('STOCK_IN','STOCK_IN_ITEM','STOCK_OUT','STOCK_OUT_ITEM');


