-- Tests for INVOICE VPD

-- Admin full
EXEC APP_CTX_PKG.set_role('ROLE_ADMIN');
SELECT COUNT(*) FROM INVOICE;
SELECT COUNT(*) FROM INVOICE_ITEM;

-- Tieptan full
EXEC APP_CTX_PKG.set_role('ROLE_TIEPTAN');
SELECT COUNT(*) FROM INVOICE;
SELECT COUNT(*) FROM INVOICE_ITEM;

-- Khach hang own only
EXEC APP_CTX_PKG.set_role('ROLE_KHACHHANG');
EXEC APP_CTX_PKG.set_customer('0911');
SELECT COUNT(*) FROM INVOICE WHERE CUSTOMER_PHONE = '0911';

-- Thukho / Kithuatvien deny
EXEC APP_CTX_PKG.set_role('ROLE_THUKHO');
SELECT COUNT(*) FROM INVOICE; -- 0
EXEC APP_CTX_PKG.set_role('ROLE_KITHUATVIEN');
SELECT COUNT(*) FROM INVOICE; -- 0


