-- Shared objects for Audit/FGA policies
-- Run under the application schema that owns the business tables (e.g., APP)

CREATE TABLE audit_alert_log (
  log_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  event_ts        TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
  db_user         VARCHAR2(128),
  os_user         VARCHAR2(128),
  machine         VARCHAR2(128),
  module          VARCHAR2(64),
  app_role        VARCHAR2(100),
  emp_id          VARCHAR2(64),
  customer_phone  VARCHAR2(64),
  object_schema   VARCHAR2(128),
  object_name     VARCHAR2(128),
  policy_name     VARCHAR2(128),
  client_identifier VARCHAR2(64),
  note            VARCHAR2(4000)
);
/
ALTER TABLE audit_alert_log ADD (
  dml_type        VARCHAR2(10),  -- INSERT, UPDATE, DELETE
  old_values      CLOB,           -- JSON format of old values
  new_values      CLOB,           -- JSON format of new values
  changed_columns  VARCHAR2(4000)  -- Comma-separated list of changed columns
);
/


