-- Roles and demo users for VPD testing
-- NOTE: Run role/user creation as a DBA (e.g., SYS AS SYSDBA) or an account with CREATE USER/ROLE privileges

-- 1) Create application roles
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_THUKHO;
CREATE ROLE ROLE_TIEPTAN;
CREATE ROLE ROLE_KITHUATVIEN;
CREATE ROLE ROLE_KHACHHANG;

-- 2) Create demo users (for testing only)
CREATE USER U_ADMIN IDENTIFIED BY "1" QUOTA UNLIMITED ON USERS;
CREATE USER U_THUKHO IDENTIFIED BY "1" QUOTA UNLIMITED ON USERS;
CREATE USER U_TIEPTAN IDENTIFIED BY "1" QUOTA UNLIMITED ON USERS;
CREATE USER U_KTV    IDENTIFIED BY "1" QUOTA UNLIMITED ON USERS;
CREATE USER U_KH     IDENTIFIED BY "1" QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO U_ADMIN, U_THUKHO, U_TIEPTAN, U_KTV, U_KH;
GRANT ROLE_ADMIN        TO U_ADMIN;
GRANT ROLE_THUKHO       TO U_THUKHO;
GRANT ROLE_TIEPTAN      TO U_TIEPTAN;
GRANT ROLE_KITHUATVIEN  TO U_KTV;
GRANT ROLE_KHACHHANG    TO U_KH;

-- 3) Grant data access on ORDERS to roles (run as schema owner of ORDERS)
-- Adjust if ORDERS is in a different schema; example assumes current schema owns ORDERS
GRANT SELECT ON ORDERS TO ROLE_ADMIN;
GRANT SELECT ON ORDERS TO ROLE_THUKHO;
GRANT SELECT ON ORDERS TO ROLE_TIEPTAN;
GRANT SELECT ON ORDERS TO ROLE_KITHUATVIEN;
GRANT SELECT ON ORDERS TO ROLE_KHACHHANG;


