-- Kiểm tra audit hiện tại
SHOW PARAMETER audit_trail;

-- Nếu chưa bật, bật audit DB + EXTENDED
ALTER SYSTEM SET audit_trail = DB,EXTENDED SCOPE=SPFILE;

-- Sau đó cần restart database
-- 1. EMPLOYEE
AUDIT INSERT, UPDATE, DELETE ON EMPLOYEE BY ACCESS;

-- 2. CUSTOMER
AUDIT INSERT, UPDATE, DELETE ON CUSTOMER BY ACCESS;

-- 3. ORDERS
AUDIT INSERT, UPDATE, DELETE ON ORDERS BY ACCESS;

-- 4. STOCK_IN
AUDIT INSERT, UPDATE, DELETE ON STOCK_IN BY ACCESS;

-- 5. STOCK_IN_ITEM
AUDIT INSERT, UPDATE, DELETE ON STOCK_IN_ITEM BY ACCESS;

-- 6. PART
AUDIT INSERT, UPDATE, DELETE ON PART BY ACCESS;

-- 7. STOCK_OUT
AUDIT INSERT, UPDATE, DELETE ON STOCK_OUT BY ACCESS;

-- 8. STOCK_OUT_ITEM
AUDIT INSERT, UPDATE, DELETE ON STOCK_OUT_ITEM BY ACCESS;

-- 9. PART_REQUEST
AUDIT INSERT, UPDATE, DELETE ON PART_REQUEST BY ACCESS;

-- 10. PART_REQUEST_ITEM
AUDIT INSERT, UPDATE, DELETE ON PART_REQUEST_ITEM BY ACCESS;

-- 11. USER_OTP_LOG
AUDIT INSERT, UPDATE, DELETE ON USER_OTP_LOG BY ACCESS;

-- 12. EMPLOYEE_SHIFT
AUDIT INSERT, UPDATE, DELETE ON EMPLOYEE_SHIFT BY ACCESS;

-- 13. CUSTOMER_APPOINTMENT
AUDIT INSERT, UPDATE, DELETE ON CUSTOMER_APPOINTMENT BY ACCESS;

-- 14. INVOICE
AUDIT INSERT, UPDATE, DELETE ON INVOICE BY ACCESS;

-- 15. INVOICE_ITEM
AUDIT INSERT, UPDATE, DELETE ON INVOICE_ITEM BY ACCESS;

-- 16. SERVICE
AUDIT INSERT, UPDATE, DELETE ON SERVICE BY ACCESS;

-- 17. ORDER_SERVICE
AUDIT INSERT, UPDATE, DELETE ON ORDER_SERVICE BY ACCESS;

-- 18. INVOICE_SERVICE
AUDIT INSERT, UPDATE, DELETE ON INVOICE_SERVICE BY ACCESS;




SELECT * 
FROM DBA_OBJ_AUDIT_OPTS
WHERE object_name IN (
    'EMPLOYEE','CUSTOMER','ORDERS','STOCK_IN','STOCK_IN_ITEM',
    'PART','STOCK_OUT','STOCK_OUT_ITEM','PART_REQUEST','PART_REQUEST_ITEM',
    'USER_OTP_LOG','EMPLOYEE_SHIFT','CUSTOMER_APPOINTMENT','INVOICE',
    'INVOICE_ITEM','SERVICE','ORDER_SERVICE','INVOICE_SERVICE'
);

SELECT
    timestamp,
    username AS db_user,
    owner AS object_schema,
    obj_name AS object_name,
    action_name,
    sql_text
FROM DBA_AUDIT_TRAIL
WHERE obj_name IN (
    'EMPLOYEE','CUSTOMER','ORDERS','STOCK_IN','STOCK_IN_ITEM',
    'PART','STOCK_OUT','STOCK_OUT_ITEM','PART_REQUEST','PART_REQUEST_ITEM',
    'USER_OTP_LOG','EMPLOYEE_SHIFT','CUSTOMER_APPOINTMENT','INVOICE',
    'INVOICE_ITEM','SERVICE','ORDER_SERVICE','INVOICE_SERVICE'
)
ORDER BY timestamp DESC;
