-- Shared objects for Audit/FGA policies
-- Run under the application schema that owns the business tables (e.g., APP)

CREATE TABLE audit_alert_log (
  log_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  event_ts        TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
  db_user         VARCHAR2(128),
  os_user         VARCHAR2(128),
  machine         VARCHAR2(128),
  module          VARCHAR2(64),
  app_role        VARCHAR2(100),
  emp_id          VARCHAR2(64),
  customer_phone  VARCHAR2(64),
  object_schema   VARCHAR2(128),
  object_name     VARCHAR2(128),
  policy_name     VARCHAR2(128),
  client_identifier VARCHAR2(64),
  note            VARCHAR2(4000)
);
/

CREATE OR REPLACE PACKAGE audit_alert_pkg AS
  PROCEDURE log_event(
    p_object_schema IN VARCHAR2,
    p_object_name   IN VARCHAR2,
    p_policy_name   IN VARCHAR2);
END audit_alert_pkg;
/

CREATE OR REPLACE PACKAGE BODY audit_alert_pkg AS
  PROCEDURE log_event(
    p_object_schema IN VARCHAR2,
    p_object_name   IN VARCHAR2,
    p_policy_name   IN VARCHAR2) IS
    v_role VARCHAR2(100) := NVL(SYS_CONTEXT('APP_CTX','ROLE_NAME'),'ROLE_UNKNOWN');
  BEGIN
    INSERT INTO audit_alert_log(
      db_user,
      os_user,
      machine,
      module,
      app_role,
      emp_id,
      customer_phone,
      object_schema,
      object_name,
      policy_name,
      client_identifier,
      note)
    VALUES(
      SYS_CONTEXT('USERENV','SESSION_USER'),
      SYS_CONTEXT('USERENV','OS_USER'),
      SYS_CONTEXT('USERENV','HOST'),
      SYS_CONTEXT('USERENV','MODULE'),
      v_role,
      SYS_CONTEXT('APP_CTX','EMP_ID'),
      SYS_CONTEXT('APP_CTX','CUSTOMER_PHONE'),
      p_object_schema,
      p_object_name,
      p_policy_name,
      SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),
      'Unauthorized DML detected via policy ' || p_policy_name);

    -- Optional hook for external alerting; replace with UTL_MAIL / REST call if needed
    DBMS_OUTPUT.PUT_LINE(
      'AUDIT_ALERT_PKG captured event for '
      || p_object_name
      || ' - policy '
      || p_policy_name
      || ' role='
      || v_role);
  EXCEPTION
    WHEN OTHERS THEN
      -- Avoid raising errors back to the DML caller; just log locally
      DBMS_OUTPUT.PUT_LINE('AUDIT_ALERT_PKG.LOG_EVENT failed: ' || SQLERRM);
  END log_event;
END audit_alert_pkg;
/


