-- Drop all FGA audit policies (both old SELECT and new INSERT/UPDATE)
-- Run as schema owner (e.g., APP)
-- This script drops all FGA policies created in the Audit folder

BEGIN
  -- ============================================
  -- Drop old SELECT policies (if they exist)
  -- ============================================
  
  -- Stock SELECT policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_IN', 'AUD_STOCK_IN_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_IN_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_STOCK_IN_SELECT not found or already dropped');
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_IN_ITEM', 'AUD_STOCK_IN_ITEM_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_IN_ITEM_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_STOCK_IN_ITEM_SELECT not found or already dropped');
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_OUT', 'AUD_STOCK_OUT_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_OUT_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_STOCK_OUT_SELECT not found or already dropped');
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_OUT_ITEM', 'AUD_STOCK_OUT_ITEM_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_OUT_ITEM_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_STOCK_OUT_ITEM_SELECT not found or already dropped');
  END;

  -- Order SELECT policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'ORDERS', 'AUD_ORDERS_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_ORDERS_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_ORDERS_SELECT not found or already dropped');
  END;

  -- Invoice SELECT policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'INVOICE', 'AUD_INVOICE_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_INVOICE_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_INVOICE_SELECT not found or already dropped');
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'INVOICE_ITEM', 'AUD_INVOICE_ITEM_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_INVOICE_ITEM_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_INVOICE_ITEM_SELECT not found or already dropped');
  END;

  -- PartRequest SELECT policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART_REQUEST', 'AUD_PART_REQUEST_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_REQUEST_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_PART_REQUEST_SELECT not found or already dropped');
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART_REQUEST_ITEM', 'AUD_PART_REQUEST_ITEM_SELECT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_REQUEST_ITEM_SELECT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('AUD_PART_REQUEST_ITEM_SELECT not found or already dropped');
  END;

  -- ============================================
  -- Drop new INSERT/UPDATE policies
  -- ============================================
  
  -- Employee policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'EMPLOYEE', 'AUD_EMPLOYEE_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_EMPLOYEE_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_EMPLOYEE_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'EMPLOYEE', 'AUD_EMPLOYEE_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_EMPLOYEE_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_EMPLOYEE_UPDATE: ' || SQLERRM);
  END;

  -- Customer policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'CUSTOMER', 'AUD_CUSTOMER_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_CUSTOMER_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_CUSTOMER_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'CUSTOMER', 'AUD_CUSTOMER_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_CUSTOMER_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_CUSTOMER_UPDATE: ' || SQLERRM);
  END;

  -- Stock INSERT/UPDATE policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_IN', 'AUD_STOCK_IN_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_IN_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_IN_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_IN', 'AUD_STOCK_IN_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_IN_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_IN_UPDATE: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_IN_ITEM', 'AUD_STOCK_IN_ITEM_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_IN_ITEM_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_IN_ITEM_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_IN_ITEM', 'AUD_STOCK_IN_ITEM_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_IN_ITEM_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_IN_ITEM_UPDATE: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_OUT', 'AUD_STOCK_OUT_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_OUT_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_OUT_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_OUT', 'AUD_STOCK_OUT_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_OUT_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_OUT_UPDATE: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_OUT_ITEM', 'AUD_STOCK_OUT_ITEM_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_OUT_ITEM_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_OUT_ITEM_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'STOCK_OUT_ITEM', 'AUD_STOCK_OUT_ITEM_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_STOCK_OUT_ITEM_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_STOCK_OUT_ITEM_UPDATE: ' || SQLERRM);
  END;

  -- Part policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART', 'AUD_PART_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_PART_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART', 'AUD_PART_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_PART_UPDATE: ' || SQLERRM);
  END;

  -- PartRequest INSERT/UPDATE policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART_REQUEST', 'AUD_PART_REQUEST_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_REQUEST_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_PART_REQUEST_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART_REQUEST', 'AUD_PART_REQUEST_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_REQUEST_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_PART_REQUEST_UPDATE: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART_REQUEST_ITEM', 'AUD_PART_REQUEST_ITEM_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_REQUEST_ITEM_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_PART_REQUEST_ITEM_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'PART_REQUEST_ITEM', 'AUD_PART_REQUEST_ITEM_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_PART_REQUEST_ITEM_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_PART_REQUEST_ITEM_UPDATE: ' || SQLERRM);
  END;

  -- Invoice INSERT/UPDATE policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'INVOICE', 'AUD_INVOICE_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_INVOICE_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_INVOICE_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'INVOICE', 'AUD_INVOICE_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_INVOICE_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_INVOICE_UPDATE: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'INVOICE_ITEM', 'AUD_INVOICE_ITEM_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_INVOICE_ITEM_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_INVOICE_ITEM_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'INVOICE_ITEM', 'AUD_INVOICE_ITEM_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_INVOICE_ITEM_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_INVOICE_ITEM_UPDATE: ' || SQLERRM);
  END;

  -- Order INSERT/UPDATE policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'ORDERS', 'AUD_ORDERS_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_ORDERS_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_ORDERS_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'ORDERS', 'AUD_ORDERS_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_ORDERS_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_ORDERS_UPDATE: ' || SQLERRM);
  END;

  -- Appointment policies
  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'CUSTOMER_APPOINTMENT', 'AUD_CUSTOMER_APPOINTMENT_INSERT');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_CUSTOMER_APPOINTMENT_INSERT');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_CUSTOMER_APPOINTMENT_INSERT: ' || SQLERRM);
  END;

  BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'CUSTOMER_APPOINTMENT', 'AUD_CUSTOMER_APPOINTMENT_UPDATE');
    DBMS_OUTPUT.PUT_LINE('Dropped: AUD_CUSTOMER_APPOINTMENT_UPDATE');
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error dropping AUD_CUSTOMER_APPOINTMENT_UPDATE: ' || SQLERRM);
  END;

  DBMS_OUTPUT.PUT_LINE('=== Finished dropping all FGA policies ===');
END;
/
