-- Tests for PART_REQUEST VPD

EXEC APP_CTX_PKG.set_role('ROLE_ADMIN');
SELECT COUNT(*) FROM PART_REQUEST;
SELECT COUNT(*) FROM PART_REQUEST_ITEM;

EXEC APP_CTX_PKG.set_role('ROLE_THUKHO');
SELECT COUNT(*) FROM PART_REQUEST;

-- Kithuatvien: own only (assumes EMP_ID=101 demo)
EXEC APP_CTX_PKG.set_role('ROLE_KITHUATVIEN');
EXEC APP_CTX_PKG.set_emp(101);
SELECT COUNT(*) FROM PART_REQUEST WHERE REQUEST_EMP_ID = 101;

-- Tieptan/Khachhang: no access
EXEC APP_CTX_PKG.set_role('ROLE_TIEPTAN');
SELECT COUNT(*) FROM PART_REQUEST; -- 0
EXEC APP_CTX_PKG.set_role('ROLE_KHACHHANG');
SELECT COUNT(*) FROM PART_REQUEST; -- 0


