-- Procedure: GET_PUBLICKEY_BY_USERNAME
-- Lấy public key của employee theo username
CREATE OR REPLACE PROCEDURE APP.GET_PUBLICKEY_BY_USERNAME (
    p_username IN  VARCHAR2,
    p_public_key OUT CLOB
) AS
BEGIN
    SELECT PUBLIC_KEY
    INTO p_public_key
    FROM APP.EMPLOYEE
    WHERE USERNAME = p_username;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_public_key := NULL;
    WHEN TOO_MANY_ROWS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Có nhiều hơn một employee trùng username: ' || p_username);
END GET_PUBLICKEY_BY_USERNAME;
/

-- Grant execute permission
GRANT EXECUTE ON APP.GET_PUBLICKEY_BY_USERNAME TO ROLE_ADMIN;
GRANT EXECUTE ON APP.GET_PUBLICKEY_BY_USERNAME TO ROLE_TIEPTAN;
GRANT EXECUTE ON APP.GET_PUBLICKEY_BY_USERNAME TO ROLE_THUKHO;
GRANT EXECUTE ON APP.GET_PUBLICKEY_BY_USERNAME TO ROLE_KITHUATVIEN;

