-TERMINAL : javac -source 8 -target 8 CryptoRSAWrapper.java



-- Tạo user
CREATE USER App IDENTIFIED BY App
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

ALTER USER App QUOTA UNLIMITED ON USERS;

-- Cấp quyền cơ bản & quyền Java
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE TABLE TO App;
GRANT CREATE SEQUENCE, CREATE TRIGGER TO App;
GRANT EXECUTE ON DBMS_CRYPTO TO App;
GRANT EXECUTE ON DBMS_FGA TO App;
GRANT EXECUTE ON DBMS_RLS TO App;
GRANT JAVAUSERPRIV TO App;
GRANT CREATE USER, ALTER USER, DROP USER TO App;
GRANT UNLIMITED TABLESPACE TO App;
GRANT CREATE SESSION TO App;
GRANT GRANT ANY ROLE, GRANT ANY PRIVILEGE TO App;


-TERMINAL : loadjava -user App/App@ORCLPDB1 -resolve CryptoRSAWrapper.class




CREATE OR REPLACE PROCEDURE RSA_GENERATE_KEYPAIR(p_size NUMBER)
AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.generateKeyPair(int)';
/

CREATE OR REPLACE FUNCTION RSA_GET_PUBLIC_KEY RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.getPublicKey() return java.lang.String';
/

CREATE OR REPLACE FUNCTION RSA_GET_PRIVATE_KEY RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.getPrivateKey() return java.lang.String';
/

CREATE OR REPLACE FUNCTION RSA_ENCRYPT(p_plain VARCHAR2, p_pub VARCHAR2) RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.encrypt(java.lang.String, java.lang.String) return java.lang.String';
/

CREATE OR REPLACE FUNCTION RSA_DECRYPT(p_cipher VARCHAR2, p_priv VARCHAR2) RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.decrypt(java.lang.String, java.lang.String) return java.lang.String';
/