-TERMINAL : javac CryptoRSAWrapper.java

CREATE USER C##CRYPTO IDENTIFIED BY crypto 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;
GRANT EXECUTE ON DBMS_CRYPTO TO C##CRYPTO;
GRANT CREATE SEQUENCE TO C##CRYPTO;
GRANT CREATE TRIGGER TO C##CRYPTO;
GRANT EXECUTE ON DBMS_FGA TO C##CRYPTO;
GRANT EXECUTE ON DBMS_RLS TO C##CRYPTO;

GRANT CREATE SESSION, CREATE PROCEDURE, CREATE TABLE TO C##CRYPTO;
GRANT JAVAUSERPRIV TO C##CRYPTO;

-TERMINAL : loadjava -user C##CRYPTO/crypto@ORCLCDB -resolve CryptoRSAWrapper.class




CREATE OR REPLACE PROCEDURE RSA_GENERATE_KEYPAIR(p_size NUMBER)
AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.generateKeyPair(int)';
/

CREATE OR REPLACE FUNCTION RSA_GET_PUBLIC_KEY RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.getPublicKey() return java.lang.String';
/

CREATE OR REPLACE FUNCTION RSA_GET_PRIVATE_KEY RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.getPrivateKey() return java.lang.String';
/

CREATE OR REPLACE FUNCTION RSA_ENCRYPT(p_plain VARCHAR2, p_pub VARCHAR2) RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.encrypt(java.lang.String, java.lang.String) return java.lang.String';
/

CREATE OR REPLACE FUNCTION RSA_DECRYPT(p_cipher VARCHAR2, p_priv VARCHAR2) RETURN VARCHAR2 AS LANGUAGE JAVA
NAME 'CryptoRSAWrapper.decrypt(java.lang.String, java.lang.String) return java.lang.String';
/