-- Roles and demo users for VPD testing
-- NOTE: Run role/user creation as a DBA (e.g., SYS AS SYSDBA) or an account with CREATE USER/ROLE privileges

-- 1) Create application roles
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_THUKHO;
CREATE ROLE ROLE_TIEPTAN;
CREATE ROLE ROLE_KITHUATVIEN;
CREATE ROLE ROLE_KHACHHANG;



GRANT CONNECT, RESOURCE TO ROLE_ADMIN, ROLE_THUKHO, ROLE_TIEPTAN, ROLE_KITHUATVIEN, ROLE_KHACHHANG;
GRANT EXECUTE ON "APP"."CHANGE_CUSTOMER_PASSWORD" TO ROLE_KHACHHANG;
GRANT EXECUTE ON "APP"."CHANGE_EPLOYEE_PASSWORD" TO ROLE_ADMIN,ROLE_KITHUATVIEN,ROLE_TIEPTAN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_EMPLOYEE_ROLES_BY_USERNAME" TO ROLE_ADMIN,ROLE_KITHUATVIEN,ROLE_TIEPTAN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."HASH_PASSWORD" TO ROLE_ADMIN,ROLE_KITHUATVIEN,ROLE_TIEPTAN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."LOGIN_EMPLOYEE" TO ROLE_ADMIN,ROLE_KITHUATVIEN,ROLE_TIEPTAN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."LOGIN_CUSTOMER" TO ROLE_KHACHHANG;
GRANT EXECUTE ON "APP"."GET_ALL_APPOINTMENTS" TO ROLE_KHACHHANG,ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."GET_ALL_ORDERS" TO ROLE_KHACHHANG,ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."CREATE_APPOINTMENT" TO ROLE_KHACHHANG;
GRANT EXECUTE ON "APP"."ASSIGN_PROFILE_TO_USER" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."ASSIGN_ROLE_PROC" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."REVOKE_ROLE_PROC" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."CREATE_PROFILE" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."CREATE_ROLE_PROC" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."DELETE_PROFILE" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."DELETE_ROLE_PROC" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ALL_ROLES" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ALL_USERS" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ALL_USERS_WITH_PROFILE" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ALL_PROFILES_WITH_LIMITS" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_PROFILE_BY_NAME" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."UPDATE_PROFILE" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ROLES_OF_USER" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_EMPLOYEE_ID_BY_USERNAME" TO ROLE_KITHUATVIEN,ROLE_TIEPTAN,ROLE_THUKHO,ROLE_ADMIN;
GRANT EXECUTE ON "APP"."LOCK_DB_USER" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."UNLOCK_DB_USER" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."CREATE_INVOICE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_ALL_IMPORTS" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_ALL_EXPORTS" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."CREATE_STOCKIN" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."CREATE_STOCKIN_ITEM" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."CREATE_STOCKOUT_TRANSACTION" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."CREATE_PART" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."SIGN_STOCKIN" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."SIGN_PDF" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."SIGN_STOCKOUT" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."UPDATE_STOCKIN_SIGNATURE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."UPDATE_STOCKIN_PDF" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_STOCKIN_PDF" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."UPDATE_STOCKOUT_SIGNATURE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."UPDATE_STOCKOUT_PDF" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_STOCKOUT_PDF" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_IMPORT_BY_ID" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_EXPORT_BY_ID" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_EMP_ID_FROM_STOCKIN" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_EMP_ID_FROM_STOCKOUT" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_EMPLOYEE_PUBLIC_KEY" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_STOCKIN_SIGNATURE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_STOCKOUT_SIGNATURE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."VERIFY_STOCKIN_SIGNATURE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."VERIFY_STOCKOUT_SIGNATURE" TO ROLE_ADMIN,ROLE_THUKHO;
GRANT EXECUTE ON "APP"."GET_ALL_PART" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ALL_PART_IN_STOCK" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_ALL_PART_REQUESTS" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_BY_ORDER_TYPE" TO ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."CREATE_ORDER" TO ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."CREATE_ORDER_SERVICE" TO ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."GET_SERVICES_BY_ORDER_ID" TO ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."GET_ALL_SERVICES" TO ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."GET_ORDER_BY_ID" TO ROLE_ADMIN,ROLE_TIEPTAN;
GRANT EXECUTE ON "APP"."CREATE_PART_REQUEST" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."CREATE_PART_REQUEST_ITEM" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."ACCEPT_PART_REQUEST" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."COMPLETE_PART_REQUEST" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."DENY_PART_REQUEST" TO ROLE_ADMIN;
GRANT EXECUTE ON "APP"."GET_PART_BY_SERIAL" TO ROLE_ADMIN;


GRANT EXECUTE ON "APP"."GET_ALL_EMPLOYEES" TO ROLE_ADMIN,ROLE_TIEPTAN;--
GRANT EXECUTE ON "APP"."REGISTER_EMPLOYEE" TO ROLE_ADMIN, --
GRANT EXECUTE ON "APP"."GET_ALL_CUSTOMERS" TO ROLE_ADMIN,






GRANT EXECUTE ON "APP"."GET_ALL_CUSTOMERS" TO ROLE_ADMIN,ROLE_TIEPTAN,ROLE_THUKHO,ROLE_KITHUATVIEN,ROLE_KHACHHANG;


GRANT EXECUTE ON "APP"."GET_EMPLOYEE_BY_ID" TO ROLE_ADMIN
GRANT EXECUTE ON "APP"."GET_EMPLOYEE_NAME_BY_ID" TO ROLE_ADMIN

GRANT EXECUTE ON "APP"."GET_EMP_ID_FROM_STOCKIN" TO ROLE_ADMIN

GRANT EXECUTE ON "APP"."GET_ORDER_BY_ID" TO ROLE_ADMIN
GRANT EXECUTE ON "APP"."GET_PART_BY_ORDERID" TO ROLE_ADMIN

GRANT EXECUTE ON "APP"."GET_PART_BY_STATUS" TO ROLE_ADMIN
GRANT EXECUTE ON "APP"."GET_PART_BY_STOCK" TO ROLE_ADMIN
GRANT EXECUTE ON "APP"."GET_PART_BY_STOCKINID" TO ROLE_ADMIN

//GRANT EXECUTE ON "APP"."GET_UNFINISHED_ORDERS" TO ROLE_ADMIN

GRANT EXECUTE ON "APP"."REGISTER_CUSTOMER" TO ROLE_ADMIN
GRANT EXECUTE ON "APP"."UPDATE_ORDER_STATUS_WAIT_PART" TO ROLE_ADMIN;




GRANT EXECUTE ON "APP"."HASH_PASSWORD_20CHARS" TO ROLE_ADMIN


